version: 2
jobs:
  build:
    docker:
      - image: martinthomson/i-d-template:latest
    working_directory: ~/draft

    steps:
      - checkout

      - run:
          name: "Set Cache Key"
          command: "date '+%Y%W' > ~/.ci-cache"

      # Prime caches for faster checkout
      - restore_cache: &git-keys
          keys:
            - git-reference-{{ checksum "~/.ci-cache" }}
      - run:
          name: "Update Cache"
          command: "git -C ~/git-reference fetch --all --prune"
      - save_cache:
          <<: *git-keys
          paths:
            - ~/git-reference

      # Build txt and html versions of drafts
      - restore_cache: &refcache-keys
          keys:
            - refcache-{{ checksum "~/.ci-cache" }}
      - run:
          name: "Build Drafts"
          command: "make 'CLONE_ARGS=--reference ~/git-reference'"
      - save_cache:
          <<: *refcache-keys
          paths:
            - ~/.cache/xml2rfc

      # Update editor's copy on gh-pages
      - run:
          name: "Update GitHub Pages"
          command: |
            if [ "${CIRCLE_TAG#draft-}" == "${CIRCLE_TAG}" ]; then
              make gh-pages
            fi

      # For tagged builds, upload to the datatracker.
      - deploy:
          name: "Upload to Datatracker"
          command: |
            if [ "${CIRCLE_TAG#draft-}" != "${CIRCLE_TAG}" ]; then
              make upload
            fi

      # Save GitHub issues
      - run:
          name: "Save GitHub Issues"
          command: "make issues || make issues DISABLE_ISSUE_FETCH=true && make gh-issues"

      # Create and store artifacts
      - run:
          name: "Create Artifacts"
          command: "make artifacts CI_ARTIFACTS=/tmp/artifacts"

      - store_artifacts:
          path: /tmp/artifacts


workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /.*?/
